version: '3.8'

services:
  # Development PostgreSQL Database
  postgres-dev:
    image: postgres:15-alpine
    container_name: parking-postgres-dev
    environment:
      POSTGRES_DB: parking_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - parking-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d parking_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development Redis Cache
  redis-dev:
    image: redis:7-alpine
    container_name: parking-redis-dev
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    volumes:
      - redis_dev_data:/data
    networks:
      - parking-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  parking-dev-network:
    driver: bridge